### ISSUE TITLE
Bogey Policy

### ISSUE THREAD

**Issue by thenetworkgrinch** [BroncBotz3481/ChargedUp2023#2]
- [x] [BogeyPolicy.java](src/main/java/frc/robot/subsystems/bogey/BogeyPolicy.java) attributes needs javadoc descriptions. Line 12-18
- [x] Class javadoc needs updated. [BogeyPolicy.java](src/main/java/frc/robot/subsystems/bogey/BogeyPolicy.java) Line: 7-9
- [x] Remove commented out code.

**Comment by Zamoa0714** [comment]
We've finished

**Comment by svs2005** [comment]
Done
