### ISSUE TITLE
Bogey Subsystem

### ISSUE THREAD

**Issue by thenetworkgrinch** [BroncBotz3481/ChargedUp2023#3]
- [x] Make the constructor [BogeySubsystem.java](src/main/java/frc/robot/subsystems/bogey/BogeySubsystem.java)  use PIDF values from [BogeyPolicy.java](src/main/java/frc/robot/subsystems/bogey/BogeyPolicy.java) 
- [x] Set the feedback encoder for the PIDController
- [x] Document the constructor using `/**`
- [x] Document the `set` function using `/**`
- [x] Document the `moveArm` function using `/**`.
- [x] Document and consider renaming the `pidMove` function using `/**`.
- [x] Document the `stopArm` function using `/**`.
- [ ] #15
- [x] Set the motor to `brake` mode in the constructor.
- [x] Factory default the motor before any configuration.

**Comment by Zamoa0714** [comment]
Is it good now?

**Comment by Zamoa0714** [comment]
Do all methods with a parameter need a @param?
